use_frameworks!

platform :ios, '12.0'

target 'NXDrawKit_Example' do
  pod 'NXDrawKit', :path => '../'
  pod 'RSKImageCropper'

#  target 'NXDrawKit_Tests' do
#    inherit! :search_paths
#    
#  end
end

post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
          end
      end
end
